parameters:
  # system
  name: arctan
  domain:
    - - -2
      - 2
  attractor_list:
    - - 1.39
    - - -1.39
  # to delete
  num_attractors: 2
  # network
  network_width: 32
  num_labels: 3
  label_threshold: 0.5
  input_dimension: 1
  # training
  seed: 3
  epochs: 500
  patience: 50
  batch_size: 100
  learning_rate: 0.001
  verbose: True 
  # data
  data_file: data/arctan_data.csv
  num_data_points: 300
  # output
  model_dir: output/arctan/models/
  log_dir: output/arctan/logs/
  output_dir: output/arctan/
  forward_exponent: 2
  backward_exponent: 2
  max_penalty: 2
  separatrix_self_penalty: 2
  base: 2
  condensation_graph:
    num_nodes: 5
    edge_list: '[[0, 1], [1, 3], [3, 5], [0, 2], [2, 4]]'
    
    
